#
# cpp-build-env/6.0.0/Dockerfile
#
# voxowl/docker-images project
#
# ubuntu 18.04
# clang 6.0.0
# cmake 3.10.2
# ninja 1.8.2
#

FROM ubuntu:18.04

RUN apt update && apt upgrade -y && apt install -y \
    clang \
    cmake \
    ninja-build
