#
# cpp-build-env/14.0.0/Dockerfile
#
# voxowl/docker-images project
#
# ubuntu 22.04
# clang 14.0.0
# cmake 3.22.1
# ninja 1.10.1
#

FROM ubuntu:22.04

RUN apt update && apt upgrade -y && apt install -y \
    clang \
    cmake \
    ninja-build
